- name: configure cisco routers
  hosts: routers:&ios_router:!R3
  connection: ansible.netcommon.network_cli
  gather_facts: no

  tasks:
    - name: Copy running configuration
      cisco.ios.ios_config:
        backup: true
        backup_options:
          dir_path: /root/backup/routers/{{ inventory_hostname }}/

